### ISSUE TITLE
Labels are not submitted

### ISSUE THREAD

**Issue by koxu1996** [gevulotnetwork/gvltctl#60]
I [submitted](https://testnet.ping.pub/firestarter/tx/d0900210647d0b30c2ef67ad1f0c4846f36f5c743e0f82e8103a95c2558678d2) the following task with `gvltctl`:

```yaml
version: v0
metadata:
  name: HC_02 - Hello World
  description: Simple hello-world task
  tags: []
  labels:
  - key: suggested_worker
    value: ff7f11b7a3e76fd7b824d7f28e4f02e585a89d537fea0f28af0e6783c2d0021b
spec:
  image: https://storage.googleapis.com/gmulot-vm/hello-v2.img
  command:
  - /hello
  args: []
  env: []
  inputContexts: []
  outputContexts: []
  storeStdout: true
  storeStderr: true
  resources:
    cpus: 100
    gpus: 0
    memory: 1000
    time: 300
```

Notice there is `suggested_worker` label. However, label does not seem to be submitted:

![Image](https://github.com/user-attachments/assets/5e17ebb3-7907-4db8-a617-7eb7b1daa29f)
